### ISSUE TITLE
Getting the flux/weight files into cvmfs instead of local 

### ISSUE THREAD

**Issue by hschellman** [MinervaExpt/MAT-MINERvA#1]
MATFluxAndReweightFiles
MParamFiles

1. need to go to cvmfs with a cron that update it - Dan  or Alex or other system expert

2. we need to find the PLOTUTILSROOT/data  references in the code and change them to link to 

$MPARAMFILES and $MATFLUXFILE  environmentals need to defined and used.  Default would be the cvmfs

Sean and Heidi will dig through the code and see where we might have to make that change away from PLOTUTILS.

**Comment by hschellman** [comment]
PLOTUTILSROOT occurs in the following:

universes/GeantHadronSystematics.cxx:1   >> $MATFLUXANDWEIGHTFILES 
universes/GeantHadronSystematics.h:1 >> $MATFLUXANDWEIGHTFILES 
universes/MinervaUniverse.cxx:1 ?? >> $MATFLUXANDWEIGHTFILES 
universes/MinervaUniverse.h:1  >> $MATFLUXANDWEIGHTFILES 
utilities/TargetUtils.cxx:2 >> $MATFLUXANDWEIGHTFILES 
weighters/MnvHadronReweight.cxx:3 >> $MATFLUXANDWEIGHTFILES 

Need to also fix in MAT

PlotUtils/FluxReweighter.cxx:7 >> $MATFLUXANDWEIGHTFILES 
PlotUtils/FluxReweighter.h:1 >> $MATFLUXANDWEIGHTFILES 
app/MakeMHRWKineRenorm.cxx:2 >> $MATFLUXANDWEIGHTFILES

**Comment by aolivier23** [comment]
Dan installed them in /cvmfs effectively today.  They exist in /grid/fermiapp and will be copied at 3:15AM each morning.  Next, we can update MAT-MINERvA/bootstrap/CMakeLists.txt to point (or symlink?) to the flux and reweight files in /cvmfs instead of checking them out.  In parallel, we need a script to update /grid/fermiapp from /cvmfs like what happens to CentralizedProductionScripts.

**Comment by hschellman** [comment]
Changed this:
#Set up MParamFiles for my laptop
export MPARAMFILESROOT=${INSTALL_DIR}/etc/MParamFiles
export MATFLUXANDWEIGHTFILES=${INSTALL_DIR}/etc/MATFluxAndReweightFiles
export MPARAMFILES=${MPARAMFILESROOT}/data

will need to change to point to the cvmfs once we decide on this. 

Now ready to make the code changes.

**Comment by AlexRaDe** [comment]
Asking Rob, he might give me a hint to do it

**Comment by aolivier23** [comment]
CMake machinery to use centralized flux files (and MParamFiles) is in place and has been through some simple tests.  I think it could be simpler and avoid symlinks, but this will have to be our first attempt.  I tested it by running the 2021 tutorial.

**Comment by aolivier23** [comment]
Alex and David just put the last piece of the puzzle, the auto-update script, in place.  It's supposed to run at 10PM Central time every day.  So, I made flux files from /cvmfs the default behavior.

This will apply to most users automatically on the GPVMs.  It will NOT clean up old flux file installations though.  It should also apply on any machine that mounts our /cvmfs area like the OSU cluster.  I hear this is possible on laptops too.  If you don't mount /cvmfs, like on a laptop out of the box, you'll continue to get 2 copies of the flux files.
